export const Terms =[
    {
        title:<small>Terms and Conditions</small>,
        terms: <div>
            These terms and conditions (the Terms and Conditions or the Agreement) set out the terms of the agreement between you as a member of GiftseaNFT and a user of the Platform (You or a Member), GiftseaNFT  Ltd (GiftseaNFT ) and, where applicable, an appointed nominee. Together GiftseaNFT  Ltd and the Nominee shall be referred to as “we” and “us”. The Platform meaning the website operated by GIFTSEANFT under the trading name GiftseaNFT.
            <small><br/><br/>
            The terms and conditions should be read in conjunction with our Terms of Website Use (www.Giftseanft.com/terms-of-website-use) and our Privacy Statement (www.Giftseanft.com/privacy-statement). Use of our Platform is conditional upon your acceptance of these terms. If you do not agree to these terms you should immediately discontinue use of our Platform.
            </small><br/><br/>
            <small>
            This Agreement will become legally binding once you have successfully undertaken the registration process and we have received satisfactory money laundering verification information.
            </small><br/><br/>
            <small>Relationship between us</small><br/><br/>
            <ol>
                <li>This Agreement is a binding contract between you, us and the Nominee (if relevant), and it sets out your and our rights and obligations with respect to your membership of GiftseaNFT and use of the Platform. In executing this Agreement, you are indicating that you agree to adhere to, and be bound by, all of its terms.</li>
                <li>In addition to this Agreement, you may enter into several other agreements with us and, if inconsistent, the terms of any agreement to which you agree after this Agreement will prevail over the terms of this Agreement.</li>
                <li>Upon executing this Agreement, you will become a Member of GiftseaNFT. In the event that you make an investment in securities through the Platform, you will also become a client of GIFTSEANFT. GIFTSEANFT will advise you of the type of client you are for regulatory purposes. An individual will, unless we notify you otherwise, be treated as a “retail” client for the purposes of the FCA (Financial Conduct Authority, www.fca.org.uk) Rules. You may provide self-certification in relation to registering as a Member. You must answer any questions entirely on your own and without the assistance of another individual. This means that the declarations set forward in the self-certification are truthful and genuinely apply to you. If you wish to change your client classification you should notify GiftseaNFT.</li>
                <li>Upon executing this Agreement, you will become a Member of GiftseaNFT. In the event that you make an investment in securities through the Platform, you will also become a client of GIFTSEANFT. GIFTSEANFT will advise you of the type of client you are for regulatory purposes. An individual will, unless we notify you otherwise, be treated as a “retail” client for the purposes of the FCA (Financial Conduct Authority, www.fca.org.uk) Rules. You may provide self-certification in relation to registering as a Member. You must answer any questions entirely on your own and without the assistance of another individual. This means that the declarations set forward in the self-certification are truthful and genuinely apply to you. If you wish to change your client classification you should notify GiftseaNFT.</li>
                <li>If you become a Member you will have the opportunity to invest in some or all of the investments available from time to time on the Platform. There may be additional terms relating to the specific investment and, where notified by us and approved by you, investments may be held through a nominee arrangement (as described in the Nominee Additional Terms).</li>
                <li>We are required to establish your identity before you are able to use the Platform. We will use third-party organisations to assist with this process at the point when you register on our Platform. By registering on our Platform you consent to us and our partner organisations using your personal information for the purposes of carrying out credit checks and other searches on you to establish your identity, your creditworthiness and your suitability to carry out Investments. We will keep records of any information obtained.</li>
                <li> If we are unable to establish your identity using these third-party methods, you must provide sufficient documentation about yourself to enable us and other relevant parties to ascertain and verify your identity. This may include providing certified copies of identification documents such as your passport, driving licence and recent utility bills, and providing personal information such as your address, residency and date of birth. The information required may change from time to time and should that prove to be the case we will notify you that additional documentation is required. Until you provide that additional documentation you will be unable to proceed to use our Platform.</li>
                <li>You authorise us to use any of your personal information which is relevant to our provision of services to you for all reasonable purposes in relation to your use of the Platform. We may retain and continue to process your personal information after the termination of this Agreement or any other agreement between you and us. Your personal information may be transferred or disclosed to and/or by third parties where necessary. This enables us to provide services to you and to discharge our obligations to third parties, including relevant stock exchanges, government agencies and regulators.</li>
                <li>With your consent, your personal information may be used by us in order to provide you with information and marketing materials in relation to our other products and services. By entering into this Agreement you confirm your wish for your personal information to be processed for these additional purposes. If you do not wish to receive marketing information please advise us in writing.</li>
                <li>We have a conflicts of interest policy which sets out the types of actual or potential conflicts of interest which may arise given the nature of our business and provides details of how these are managed. Further details and updates of this policy can be provided on request.</li>
                <small>Miscellaneous</small><br/><br/>
                <li> Termination: An Investor may terminate and close their account with GIFTSEANFT at any time by giving at least 7 (seven) days' written notice to GIFTSEANFT. GIFTSEANFT may in its sole discretion, at any time, immediately terminate an Investor’s account by written notice to the Investor. The Investor accepts and acknowledges that GIFTSEANFT will be entitled to retain such information about the Investor and any Investments, as necessary, in order to comply with their obligations to the relevant regulatory bodies.</li>
                <li>Amendment: These Terms and Conditions may be varied by us from time to time. If these Terms and Conditions are varied we will notify you by posting the revised terms on the Platform and contacting you via email to inform you of the revised terms. In the event that additional terms or annexes are appended to the terms in relation to specific investment types we will post these additional terms on the Platform, but will not contact you via email to inform you.</li>
                <li> Entire Agreement: These Terms and Conditions, together with the Terms of Website Use and the Privacy Statement constitute the entire agreement between us, and you acknowledge that you have not relied upon any representations, statements or pre-contractual statements that are not expressly set out in these terms.</li>
                <li>Third-Party Rights: Subject to the following sentence, this Agreement does not confer any rights on any person or party (other than the parties to this agreement) pursuant to the Contracts (Rights of Third Parties) Act 1999. With the prior written consent of GIFTSEANFT given in its sole discretion, any Relevant Person, any Company and/or any of such Company's directors, employees, consultants, agents or advisers, shall be entitled to enforce all of the rights and benefits under this agreement at all times as if party to this agreement.</li>
                <li>Communications and Notices: Any notice given by any party under or in connection with these terms shall be in writing and in English, and shall be sent by the relevant party for the attention of the contact and to the address as notified by the party, from time to time. It shall be delivered by email, or sent by pre-paid first-class post or recorded delivery, and shall be deemed received as set out below. Delivery of a notice is deemed to have taken effect provided that all other requirements in this clause have been satisfied, if delivered by email, upon sending; or if sent by pre-paid first class post, recorded delivery or special delivery to an address in the UK, at 9:00am on the second business day after posting. If deemed receipt under this Clause 16 would occur outside business hours (meaning outside 9:00am to 5:30pm Monday to Friday on a day that is not a public holiday in England and a day when the banks in the city of London are open for business) then receipt is deemed to take place at 9:00am on the day when business next starts in England. To prove service it is sufficient to prove that if delivered by email the email was sent to the correct address (being contactus@GiftseaNFT.com or the email address associated with your account), and if delivered by post, the envelope containing the notice or other communication was properly addressed, paid for and posted.</li>
                <li>Further Assurance: You shall from time to time (both during the continuance of these terms and after its termination) do all such acts and execute all such documents as may be reasonably necessary in order to give effect to the provisions of these terms.</li>
                <li>Costs: Your and our costs and expenses (including any professional, legal and accountancy expenses) of the preparation, negotiation and execution of any Investment and/or any associated documentation shall be borne by you and us respectively.</li>
                <li>Survival: All disclaimers, indemnities and exclusions in these terms shall survive termination of these terms for any reason, as shall any other provisions of these terms that by their nature are intended to survive such termination.</li>
                <li> Complaints: Should you have any complaints in relation to your use of the Platform, please notify us by email at contactus@GiftseaNFT.com. We will aim to acknowledge your complaint promptly, investigate the circumstances and report the results to you. If your complaint is unresolved 8 (eight) weeks from the date you first made the complaint, you may refer it directly to The Financial Ombudsmen Service (FOS). The address of FOS is Exchange Tower, London E14 9GIFTSEANFT, www.financial-ombudsman.org.uk. Certain customers, such as larger companies and trusts, may not have access to the FOS.</li>
                <li>Time of Essence: Time shall be of the essence in relation to all matters arising under or pursuant to these terms.</li>
                <li>No Waiver. No failure or delay by you or us in exercising any of our rights under these terms shall be deemed to be a waiver of that right, and no waiver by you or us of a breach of any provision of these terms shall be deemed to be a waiver of any subsequent breach of the same or any other provision.</li>
                <li> Severability. If any provision of these Terms and Conditions is held by any court or other competent authority to be invalid or unenforceable, in whole or in part, these Terms and Conditions shall continue to be valid as to its other provisions and the remainder of the affected provision.</li>
                <li>No Partnership. These Terms and Conditions shall not be construed so as to create a partnership or joint venture between you and us. Nothing in these Terms and Conditions shall be construed so as to constitute you and us as agents of one another.</li>
                <li>Assignment. These Terms and Conditions shall be binding on and inure to the benefit of each party and their respective successors and assigns. Any party (other than GIFTSEANFT) shall not assign or sub-contract any of its rights or obligations under these terms (in whole or in part) without the prior written consent of GIFTSEANFT. GIFTSEANFT shall be entitled to assign or sub-contract any of its rights or obligations under these Terms and Conditions in whole or in part.</li>
                <li> Force Majeure. GIFTSEANFT shall not be in breach of these Terms and Conditions if there is, and shall not be liable or have responsibility of any kind for any loss or damage incurred by you as a result of, any total or partial failure, interruption or delay in performance of our duties and obligations occasioned by any act of God, fire, act of government, state, governmental or supranational body or regulatory authority or war, civil commotion, terrorism, failure of any internet or computer system, interruptions of power supplies, labour disputes of whatever nature or any other reason (whether or not similar in kind to any of the above) beyond our reasonable control.</li>
                <li> Governing Law and Jurisdiction. These Terms and Conditions (and any dispute or claim relating to it or its subject matter (including non-contractual claims) is governed by and is to be construed in accordance with English law. The parties irrevocably agree that the courts of England and Wales shall have exclusive jurisdiction to settle any claim, dispute or issue (including non-contractual claims) which may arise out of or in connection with this agreement.</li>
                <li></li>
            </ol>
            </div>,
        privacy:<small>

        </small>
    }
]










